version: '3'
services:
  eureka:
    build: netflix-eureka-naming-server
    ports:
      - "8761:8761"
  zuul:
    build: netflix-zuul-api-gateway-server
    links:
      - eureka
    ports:
      - "8765:8765"
  conversion:
    build: currency-conversion-service
    links:
     - eureka
    ports:
      - "8100:8100"
  exchange:
    build: currency-exchange-service
    links:
     - eureka
    ports:
      - "8000:8000"